### ISSUE TITLE
How To Deploy on my own Server?

### ISSUE THREAD

**Issue by kjboa** [willwull/saturnus#92]
Hi, i love this project and have been using it as my main reddit client for a while now. I've got  the needed api keys and cloned the github repo, what should i do next in order to get it working under a certain port number? Help would be greatly appreciated since i am a total noob

**Comment by willwull** [comment]
Hi @kjboa! Sorry for the late reply, I completely missed this issue somehow.

When you say you're a complete n00b, is this as in "knows no web development at all"? Can you give me some more context on your end goal, why are you trying to run it on a certain port number? 

Also, out of curiosity how did you find this project? I don't think I've mentioned it anywhere online lol

**Comment by kjboa** [comment]
Hi, i found your project trough google. I put in opensource reddit web client or something like that and this repo showed up. I do selfhost things on my server using docker and know linux but i have absolutly no idea how to create something like you did it. I was trying to selfhost your project so i could have my own version and maybe customize it. So i posted the same question from this issue also on reddit (https://www.reddit.com/r/selfhosted/comments/mo1eob) and got a guide as an answer. I followed it but gave up at the replace all icons part. For now i think i'm gonna stick with your hosted version.

**Comment by willwull** [comment]
@kjboa Okay got it! Yeah I realize my readme isn't the most helpful haha, I didn't really think about anyone other than me reading it 😅 

So the general gist of the top voted comment is correct, the basic setup is

1. clone the repo
2. set up the .env file
3. set up the npm token for font awesome
4. npm install
5. npm run build

The project will be compiled into a folder called build which you can host using a static web server, there's no backend.

But yeah this is pretty much not doable unless you have a font awesome pro key unfortunately. I'll try to find some time to get rid of this dependency and replace all icons so you won't need to do this step. My own pro key actually expired, so I can't even run this project myself 😛 

I'm currently a bit slammed IRL but I can let you know once I've fixed this and I can try helping you if you still want to self-host this :)
